apiVersion: apps/v1
kind: Deployment
metadata:
  name: digit-recognition-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digit-recognition
  template:
    metadata:
      labels:
        app: digit-recognition
    spec:
      containers:
        - name: digit-recognition
          image: havilash/digit-recognition:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: digit-recognition-service
spec:
  selector:
    app: digit-recognition
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
